name: CI

on: 
  push:
    branches: 
      - main
      - 'spacy-3-8'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test ${{ matrix.os }} / ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
          python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        uv sync --all-extras
        uv pip install pip
    
    - name: Download spaCy model
      run: uv run python -m spacy download en_core_web_trf
    
    - name: Run tests
      run: uv run pytest